#!/usr/bin/env bash
# Build the Lean-into-Go spike: a single cgo binary that calls Kue's real
# evaluator in-process. Run from the repo root or anywhere — paths are derived.
#
# Steps:
#   1. lake build kue        — ensure Kue's C objects + oleans exist.
#   2. lean --c / leanc -c    — compile the spike module to an object.
#   3. ar rcs                 — archive Spike.o + all Kue objects (sans Main)
#                               into one static lib the cgo link pulls from.
#   4. generate cgo_flags.go  — platform LDFLAGS, derived from leanc.
#   5. go build               — link the Go binary against the archive + the
#                               Lean runtime libs.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SPIKE_DIR="$REPO_ROOT/spike"
cd "$REPO_ROOT"

LEAN_PREFIX="$(lean --print-prefix)"
LEAN_LIB="$LEAN_PREFIX/lib/lean"
LEAN_SYSLIB="$LEAN_PREFIX/lib"

echo "==> [1/5] lake build kue (objects + oleans)"
lake build kue >/dev/null

echo "==> [2/5] compile spike module to object"
# Lean-generated C + object go under gen/ so cgo (which compiles every .c in
# the package dir) never sees Spike.c — it's already in the archive.
GEN="$SPIKE_DIR/gen"
mkdir -p "$GEN"
lake env lean --c="$GEN/Spike.c" "$SPIKE_DIR/Spike.lean"
lake env leanc -c -o "$GEN/Spike.o" "$GEN/Spike.c"

echo "==> [3/5] archive Spike.o + all Kue objects into libkuespike.a"
# Every Kue C object EXCEPT Main (which defines its own main()/initializer).
# Portable across bash 3.2 (macOS) — no mapfile.
ARCHIVE="$SPIKE_DIR/libkuespike.a"
rm -f "$ARCHIVE"
ar rcs "$ARCHIVE" "$GEN/Spike.o"
N=1
while IFS= read -r obj; do
  ar q "$ARCHIVE" "$obj"
  N=$((N + 1))
done < <(find "$REPO_ROOT/.lake/build/ir" -name '*.c.o.export' ! -name 'Main.c.o.export')
ranlib "$ARCHIVE" 2>/dev/null || ar s "$ARCHIVE"
echo "    archived $N objects -> $ARCHIVE"

echo "==> [4/5] generate cgo_flags.go (platform LDFLAGS)"
# The Lean runtime + C++ stdlib + system libs leanc links. These MIRROR
# `leanc --print-ldflags` for the platform — the empirical authority. The two
# platforms diverge sharply in the C++ stdlib:
#   macOS: links the SYSTEM libc++ (`-lc++`) from /usr/lib.
#   Linux: the Lean toolchain ships + statically links its OWN libc++
#          (`-lc++ -lc++abi` from $PREFIX/lib, NOT GNU libstdc++). Linking
#          `-lstdc++` instead leaves `std::__1::` (libc++ ABI) symbols in
#          libleanrt.a unresolved — that was the Linux blocker. Linux also
#          needs -lpthread -ldl -lrt, and --start-group/--end-group around the
#          mutually-referential Lean archives.
case "$(uname -s)" in
  Darwin)
    CXX_FLAGS="-lc++"
    SYS_FLAGS="-lm"
    GROUP_OPEN=""; GROUP_CLOSE=""
    ;;
  *)
    # libc++/libc++abi live in $PREFIX/lib (already on -L via LEAN_SYSLIB) as
    # BOTH .a and .so. Force the STATIC archives with -Bstatic/-Bdynamic (mirrors
    # leanc's own recipe) — otherwise the linker prefers libc++.so.1, which the
    # runtime loader can't find (it's not on the system ld path), and the binary
    # dies with "libc++.so.1: cannot open shared object file". Static = the
    # binary is self-contained, matching the macOS half.
    CXX_FLAGS="-Wl,-Bstatic -lc++ -lc++abi -Wl,-Bdynamic"
    SYS_FLAGS="-lpthread -ldl -lrt -lm"
    GROUP_OPEN="-Wl,--start-group"; GROUP_CLOSE="-Wl,--end-group"
    ;;
esac

cat > "$SPIKE_DIR/cgo_flags.go" <<EOF
// Code generated by build.sh. DO NOT EDIT.
package main

// #cgo CFLAGS: -I${LEAN_PREFIX}/include
// #cgo LDFLAGS: ${ARCHIVE}
// #cgo LDFLAGS: -L${LEAN_LIB} -L${LEAN_SYSLIB}
// #cgo LDFLAGS: ${GROUP_OPEN} -lleancpp -lleanrt -lInit -lStd -lLean ${GROUP_CLOSE}
// #cgo LDFLAGS: -lgmp -luv ${CXX_FLAGS} ${SYS_FLAGS}
import "C"
EOF

echo "==> [5/5] go build"
( cd "$SPIKE_DIR" && go build -o spike-bin . )
echo "    built $SPIKE_DIR/spike-bin"
echo
echo "==> run"
"$SPIKE_DIR/spike-bin"
