import Kue.Zip
import Kue.Sha256

/-!
# ZIP reader golden check (B3d-5z, real DEFLATE path)

Drives the pure `Kue.Zip.readZip` over a REAL cached cue module zip (`testdata/zip/module.zip`,
a small `prodigy9.co/defs` release — 69 flat files, all DEFLATE) and cross-checks the extracted
content against an independently-produced ground truth `testdata/zip/module.zip.sha256` (one
`<sha256>  <name>` line per file, generated by `unzip -p <zip> <name> | shasum -a 256` — an
extractor Kue's code does not share). Exercises the real-DEFLATE + CRC-32-verification path end
to end through the binary (native_decide pins stay small).

Run by `scripts/check-fixtures.sh`:
  lake env lean --run scripts/check-zip.lean <abs testdata/zip dir>

No network; READ-only over the committed fixtures. Exit 0 ⇒ the file list + every file's
content hash match the ground truth (in central-directory order); non-zero ⇒ a printed diff.
-/

open Kue

/-- Parse the ground-truth `<sha256>  <name>` lines (two spaces) into `(name, sha256)` pairs. -/
def parseSums (text : String) : List (String × String) :=
  text.trimAscii.toString.splitOn "\n" |>.filterMap (fun line =>
    match line.splitOn "  " with
    | hash :: rest => some (String.intercalate "  " rest, hash)
    | [] => none)

def main (args : List String) : IO UInt32 := do
  match args with
  | [dir] => do
    let zipPath := s!"{dir}/module.zip"
    let sumsPath := s!"{dir}/module.zip.sha256"
    let bytes ← IO.FS.readBinFile zipPath
    let sumsText ← IO.FS.readFile sumsPath
    let expected := parseSums sumsText
    match Zip.readZip bytes with
    | .error e =>
      IO.eprintln s!"  FAIL: readZip errored: {e}"
      pure 1
    | .ok files =>
      let actual := files.map (fun (n, c) => (n, Sha256.hex (Sha256.sha256 c)))
      if actual == expected then
        IO.println s!"  ok: readZip extracts {files.length} files, all CRC-verified, hashes match ground truth"
        IO.println "zip golden ok"
        pure 0
      else
        IO.eprintln s!"  FAIL: extracted hashes/order differ from ground truth"
        IO.eprintln s!"    expected {expected.length} files, got {actual.length}"
        for ((an, ah), (en, eh)) in actual.zip expected do
          if an != en || ah != eh then
            IO.eprintln s!"    mismatch: got ({an},{ah}) expected ({en},{eh})"
        pure 1
  | _ =>
    IO.eprintln "usage: lake env lean --run scripts/check-zip.lean <testdata/zip dir>"
    pure 1
