#!/usr/bin/env python3
"""Generate Kue/CaseTable.lean — BMP simple case-mapping tables for strings.ToUpper/ToLower.

PROVENANCE / why this exists
----------------------------
Lean core's `Char.toUpper`/`toLower` are ASCII-only and Kue has no external deps (no
Std/Batteries/Mathlib), so full Unicode case mapping needs a data table. CUE's
`strings.ToUpper`/`ToLower` mirror Go's `unicode.ToUpper`/`ToLower` — a pure rune-wise
SIMPLE 1:1 case mapping (no length-changing special-casing like German ß→SS). We derive
the table from the LOCAL `cue` binary oracle (READ-ONLY, NO network): the oracle is queried
over the whole Basic Multilingual Plane and the resulting src→dst pairs are emitted as two
sorted Lean arrays. Unicode case mapping is not a cue-buggy area, so the oracle is a sound
data source here; the Unicode standard's full case folding (ß→SS, locale rules, final
sigma) remains the principled long tail, documented as a spec-gap.

Re-run to regenerate (idempotent):  scripts/gen-case-table.py
Requires the local oracle at /Users/chakrit/go/bin/cue (v0.16.x).
"""

import json
import subprocess
import sys
from pathlib import Path

CUE = "/Users/chakrit/go/bin/cue"
OUT = Path(__file__).resolve().parent.parent / "Kue" / "CaseTable.lean"

# BMP scalar code points the oracle can safely round-trip in a CUE string literal.
# Excluded points have no case mapping anyway (the identity-on-miss default covers them).
EXCLUDED_SINGLETONS = {0x00, 0xFEFF}  # NUL and BOM are illegal in a cue string literal.


def probeable(cp: int) -> bool:
    if 0xD800 <= cp <= 0xDFFF:           # surrogates are not scalar values
        return False
    if cp in EXCLUDED_SINGLETONS:
        return False
    if cp < 0x20 or 0x7F <= cp <= 0x9F:  # C0/C1 controls + DEL: no case mapping, some illegal
        return False
    return True


def cue_escape(text: str) -> str:
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        else:
            out.append(ch)
    return "".join(out)


def query_oracle(code_points: list[int]) -> tuple[list[int], list[int]]:
    source = "".join(chr(cp) for cp in code_points)
    cue_src = (
        'import "strings"\n'
        "u: strings.ToUpper(src)\n"
        "l: strings.ToLower(src)\n"
        'src: "' + cue_escape(source) + '"\n'
    )
    probe = OUT.parent.parent / ".case-table-probe.cue"
    probe.write_text(cue_src)
    try:
        result = subprocess.run(
            [CUE, "export", str(probe)], capture_output=True, text=True, check=False
        )
    finally:
        probe.unlink(missing_ok=True)
    if result.returncode != 0:
        sys.exit(f"cue oracle failed:\n{result.stderr}")
    data = json.loads(result.stdout)
    upper = [ord(ch) for ch in data["u"]]
    lower = [ord(ch) for ch in data["l"]]
    return upper, lower


def diff_map(src_points: list[int], mapped: list[int]) -> dict[int, int]:
    if len(src_points) != len(mapped):
        sys.exit("oracle returned a non-1:1 mapping — strings case map is not simple")
    return {s: m for s, m in zip(src_points, mapped) if s != m}


# A single huge `#[…]` literal overflows elaboration recursion (it desugars to nested
# `List.cons`). Emit fixed-size chunk arrays `++`-joined instead: each chunk literal stays
# well under the recursion bound, and `Array.append` builds the whole iteratively at runtime.
CHUNK = 128


def emit_array(name: str, mapping: dict[int, int]) -> str:
    pairs = [(s, d) for s, d in sorted(mapping.items())]
    chunks = [pairs[i : i + CHUNK] for i in range(0, len(pairs), CHUNK)]
    lines = []
    chunk_names = []
    for idx, chunk in enumerate(chunks):
        chunk_name = f"{name}Chunk{idx}"
        chunk_names.append(chunk_name)
        body = ",\n".join(f"  (0x{s:04X}, 0x{d:04X})" for s, d in chunk)
        lines.append(f"private def {chunk_name} : Array (UInt32 × UInt32) := #[\n{body}\n]")
    joined = " ++ ".join(chunk_names)
    lines.append(f"def {name} : Array (UInt32 × UInt32) := {joined}")
    return "\n\n".join(lines)


def main() -> None:
    code_points = [cp for cp in range(0x0000, 0x10000) if probeable(cp)]
    upper, lower = query_oracle(code_points)
    upper_map = diff_map(code_points, upper)
    lower_map = diff_map(code_points, lower)

    header = f"""\
-- GENERATED by scripts/gen-case-table.py — DO NOT EDIT BY HAND.
-- BMP simple 1:1 case-mapping tables for `strings.ToUpper`/`ToLower`, derived from the
-- local `cue` v0.16.x oracle (READ-ONLY, no network). Each array is sorted ascending by
-- the source code point so `CaseTable.lookup` can binary-search it. A code point absent
-- from a table maps to itself (identity). Full Unicode special-casing (ß→SS, locale ı/İ,
-- final sigma) is out of scope — see docs/spec/compat-assumptions.md. Regenerate via the
-- generator script. ToUpper covers {len(upper_map)} code points; ToLower covers {len(lower_map)}.

namespace Kue.CaseTable
"""
    footer = "\nend Kue.CaseTable\n"
    body = (
        emit_array("upperEntries", upper_map)
        + "\n\n"
        + emit_array("lowerEntries", lower_map)
    )
    OUT.write_text(header + "\n" + body + "\n" + footer)
    print(f"wrote {OUT} — ToUpper {len(upper_map)} entries, ToLower {len(lower_map)} entries")


if __name__ == "__main__":
    main()
