import Kue.Zip

--
-- # ZIP reader + DEFLATE inflate + CRC-32 tests (B3d-5z)
--
-- `native_decide`/`#guard` pins for the pure ZIP container parse, the RFC 1951 inflate core, and
-- the zip CRC-32. Kept SMALL (native-compiled, so a large in-kernel inflate is slow) — the big
-- real-DEFLATE golden goes through the compiled binary in `scripts/check-zip.lean`.
--
-- Ground truth (independently produced, NOT self-generated by the code under test):
-- - **CRC-32** standard vectors: `crc32("") = 0`, `crc32("123456789") = 0xCBF43926` (the canonical
-- CRC-32/ISO-HDLC check value), cross-checked with Python `zlib.crc32`.
-- - **Raw-DEFLATE byte vectors** produced by Python `zlib.compressobj(..., wbits=-15)`
-- (raw deflate): a fixed-Huffman literal run, a fixed-Huffman LZ77 back-reference (repeated
-- text), and a dynamic-Huffman block — an encoder Kue's inflate does not share, so decoding them
-- back to the original text is a genuine cross-check.
-- - **Synthetic ZIP archives** produced by the system `zip` tool: a STORED archive (`zip -0`) and a
-- DEFLATE archive (`zip -9`), decoded back to their `(name, contents)` pair.
--

namespace Kue
namespace Zip

-- ## helpers

-- A `ByteArray` from a literal byte list.
def bytes (l : List Nat) : ByteArray := ⟨(l.map UInt8.ofNat).toArray⟩

-- Inflate a raw-deflate byte list to a `String` (or an error marker), for the pins below.
def inflateStr (l : List Nat) : String :=
  match Inflate.inflate (bytes l) with
  | .ok b => String.fromUTF8! b
  | .error e => s!"ERR:{e}"

-- ## CRC-32 standard vectors

-- CRC-32 of the empty input is 0.
theorem crc32_empty : (crc32 (bytes []) == 0) = true := by native_decide

-- CRC-32 of "123456789" is the canonical check value 0xCBF43926.
theorem crc32_check :
    (crc32 (bytes [49,50,51,52,53,54,55,56,57]) == 0xCBF43926) = true := by native_decide

-- "hi" → 0xd8932aac (cross-checked: python zlib.crc32(b"hi")).
theorem crc32_hi : (crc32 (bytes [104,105]) == 0xd8932aac) = true := by native_decide

-- ## inflate — bit reader / Huffman unit behavior via whole-block decode
--
-- A fixed-Huffman literal run (`zlib` raw deflate, Z_FIXED).
theorem inflate_fixed_literals :
    (inflateStr [243,72,205,201,201,215,81,8,207,47,202,73,81,4,0] == "Hello, World!")
      = true := by native_decide

-- A fixed-Huffman block with an LZ77 back-reference (the repeated "abc" run, dist=3).
theorem inflate_fixed_backref :
    (inflateStr [75,76,74,78,68,69,0] == "abcabcabcabcabcabc") = true := by native_decide

-- A dynamic-Huffman block (the code-length-code preamble + RLE-coded lengths path).
theorem inflate_dynamic :
    (inflateStr
      [43,201,72,85,40,44,205,76,206,86,72,42,202,47,207,83,72,203,175,80,200,42,205,45,40,
       86,200,47,75,45,82,40,1,74,231,36,86,85,42,164,228,167,235,129,121,196,42,6,0]
      == "the quick brown fox jumps over the lazy dog. the quick brown fox jumps over the lazy dog.")
      = true := by native_decide

-- The empty raw-deflate stream inflates to empty.
theorem inflate_empty : (inflateStr [3,0] == "") = true := by native_decide

-- ## back-reference / overlapping copy
--
-- A dist=1 run-length fill ("aaaa...") exercises the overlapping-copy path: each copied byte
-- must be visible to the next copy. Raw deflate of 8×'a'.
theorem inflate_rle :
    (inflateStr [75,76,132,1,0] == "aaaaaaaaaa") = true := by native_decide

-- ## ZIP container — synthetic archives (system `zip`)

-- The STORED archive `zip -0` of a 2-byte file `a.txt` = "hi".
def storedZip : List Nat :=
  [80,75,3,4,10,0,0,0,0,0,147,2,218,92,172,42,147,216,2,0,0,0,2,0,0,0,5,0,0,0,97,46,116,120,
   116,104,105,80,75,1,2,30,3,10,0,0,0,0,0,147,2,218,92,172,42,147,216,2,0,0,0,2,0,0,0,5,0,0,
   0,0,0,0,0,0,0,0,0,164,129,0,0,0,0,97,46,116,120,116,80,75,5,6,0,0,0,0,1,0,1,0,51,0,0,0,37,
   0,0,0,0,0]

-- The DEFLATE archive `zip -9` of an 18-byte file `b.txt` = "abcabc…" (forces a back-ref).
def deflateZip : List Nat :=
  [80,75,3,4,20,0,2,0,8,0,147,2,218,92,4,192,38,220,7,0,0,0,18,0,0,0,5,0,0,0,98,46,116,120,
   116,75,76,74,78,68,69,0,80,75,1,2,30,3,20,0,2,0,8,0,147,2,218,92,4,192,38,220,7,0,0,0,18,
   0,0,0,5,0,0,0,0,0,0,0,1,0,0,0,164,129,0,0,0,0,98,46,116,120,116,80,75,5,6,0,0,0,0,1,0,1,0,
   51,0,0,0,42,0,0,0,0,0]

-- Read a synthetic zip to its `(name, string-content)` pairs (`none` on error).
def readZipStr (l : List Nat) : Option (List (String × String)) :=
  (readZip (bytes l)).toOption.map (·.map (fun (n, c) => (n, String.fromUTF8! c)))

-- The STORED archive decodes to its one file, CRC-verified.
theorem readZip_stored :
    (readZipStr storedZip == some [("a.txt", "hi")]) = true := by native_decide

-- The DEFLATE archive decodes to its one (inflated, CRC-verified) file.
theorem readZip_deflate :
    (readZipStr deflateZip == some [("b.txt", "abcabcabcabcabcabc")]) = true := by native_decide

-- ## error paths (typed, never silent)

-- A non-zip (no EOCD) errors.
theorem readZip_not_a_zip :
    (match readZip (bytes [1,2,3,4]) with | .error _ => true | .ok _ => false) = true := by
  native_decide

-- A reserved DEFLATE block type (BTYPE=3, first byte 0b110 = 6) errors, never hangs.
theorem inflate_reserved_btype :
    (match Inflate.inflate (bytes [6,0]) with | .error _ => true | .ok _ => false) = true := by
  native_decide

-- ## adversarial reject branches (B3d-A2) — every malformed archive/stream is provably REJECTED
--
-- A malformed cue-module archive must never silently mis-decode or wrongly succeed — that would
-- be a soundness hole in the registry-fetch integrity path. We pin every adversarial reject
-- branch to its EXACT typed error (not just "is error"): a wrong branch firing (a different
-- message) fails the pin, so these guard against a reject silently moving.
--
-- Malformed DEFLATE bit-streams were bit-crafted (LSB-first packing, MSB-first Huffman codes)
-- and cross-checked against Python `zlib.decompressobj(wbits=-15)`, which independently rejects
-- every one (D1/D3/D4/DD1/DD4 as "invalid …"; DD2/DD3 truncate). Malformed ZIPs are single-field
-- mutations of the known-good `storedZip`, so the offset being corrupted is self-evident.

-- Error string of an inflate attempt (`"OK"` on unexpected success), for exact-message pins.
def inflErr (l : List Nat) : String :=
  match Inflate.inflate (bytes l) with | .ok _ => "OK" | .error e => e

-- Error string of a `readZip` attempt (`"OK"` on unexpected success).
def zipErr (l : List Nat) : String :=
  match readZip (bytes l) with | .ok _ => "OK" | .error e => e

-- ### DEFLATE (RFC 1951) reject branches

-- STORED block with LEN/NLEN not one's-complement (RFC 1951 §3.2.4). Bytes: final STORED header,
-- byte-align, LEN=2, NLEN=0 (should be ~2 = 0xFFFD).
theorem inflate_stored_len_nlen :
    (inflErr [1,2,0,0,0] == "inflate: STORED block LEN/NLEN mismatch") = true := by native_decide

-- Fixed-Huffman back-reference whose distance (2) points before the start of the 1-byte output
-- (distance-too-far-back). A malformed backref must error, never read garbage/underflow.
theorem inflate_dist_too_far :
    (inflErr [75,4,66] == "inflate: back-reference distance 2 exceeds output") = true := by
  native_decide

-- Fixed-Huffman distance code 31 (0b11111) — the fixed distance table defines only symbols 0..29,
-- so codes 30/31 are invalid (RFC 1951 §3.2.6). Decode must reject.
theorem inflate_invalid_dist_code :
    (inflErr [75,76,76,4,126] == "inflate: invalid distance code") = true := by native_decide

-- Fixed-Huffman literal/length symbol 286 — in the fixed table's code space but assigned no
-- meaning by the spec (only 257..285 are length codes). Must reject, not treat as a length.
theorem inflate_litlen_symbol_oor :
    (inflErr [27,3] == "inflate: literal/length symbol 286 out of range") = true := by
  native_decide

-- Dynamic block with all code-length-code lengths zero ⇒ empty preamble Huffman table ⇒ the
-- first code-length code cannot decode (bad dynamic-table code-length sequence).
theorem inflate_dynamic_bad_clc :
    (inflErr [5,0,0,0,0] == "inflate: invalid code-length code in dynamic preamble") = true := by
  native_decide

-- Dynamic block with an incomplete literal/length table (only symbol 0 defined, length 2), fed a
-- code that matches no symbol ⇒ invalid literal/length code.
theorem inflate_dynamic_invalid_litlen :
    (inflErr
      [5,192,1,4,0,0,0,128,160,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,26]
      == "inflate: invalid literal/length code") = true := by native_decide

-- Dynamic block whose distance table defines symbol 30 (HDIST=30) — RFC 1951 reserves distance
-- symbols 30/31 (no base value). Using one must reject before any back-reference copy.
theorem inflate_dynamic_dist_symbol_oor :
    (inflErr
      [13,158,1,4,0,0,0,64,2,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,14]
      == "inflate: distance symbol 30 out of range") = true := by native_decide

-- Dynamic block with a 1-bit literal code and NO end-of-block, truncated: past-end zero bits
-- decode to that literal forever. The fuel guard must fire a typed error (proving no hang),
-- not loop — the whole point of the explicit fuel bound.
theorem inflate_block_fuel_exhausted :
    (inflErr
      [5,192,1,4,0,0,0,0,144,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,1]
      == "inflate: block exhausted fuel (truncated or missing end-of-block)") = true := by
  native_decide

-- ### ZIP container (PKWARE APPNOTE) reject branches — single-field mutations of `storedZip`
-- (local hdr @0, central-directory hdr @37, EOCD @88).

-- A truncated/short archive (< 22 bytes, no room for an EOCD) is rejected as not-a-zip.
theorem readZip_truncated :
    (zipErr [80,75,3,4,10] == "zip: no End-Of-Central-Directory record (not a zip / truncated)")
      = true := by native_decide

-- Corrupt the central-directory header signature (`PK\x01\x02` byte @38): the CD walk rejects it.
theorem readZip_bad_cd_sig :
    (zipErr (storedZip.set 38 0)
      == "zip: bad central-directory header signature at offset 37") = true := by native_decide

-- Set the CD compression-method field (@47) to 12 (BZIP2) — not STORED/DEFLATE. Typed reject at
-- parse time, never a silent skip.
theorem readZip_unsupported_method :
    (zipErr (storedZip.set 47 12)
      == "zip: unsupported compression method 12 (only STORED/DEFLATE)") = true := by native_decide

-- Corrupt the local file header signature (`PK\x03\x04` byte @1): reject when locating the data.
theorem readZip_bad_local_sig :
    (zipErr (storedZip.set 1 0)
      == "zip: bad local file header signature for a.txt") = true := by native_decide

-- Corrupt the CD CRC-32 low byte (@53, 0xAC→0x53): the integrity gate rejects the mismatch.
theorem readZip_crc_mismatch :
    (zipErr (storedZip.set 53 83)
      == "zip: a.txt CRC-32 mismatch (got 3633523372, expected 3633523283)") = true := by
  native_decide

-- Bump the CD uncompressed-size field (@61, 2→3): the size gate rejects the discrepancy.
theorem readZip_size_mismatch :
    (zipErr (storedZip.set 61 3)
      == "zip: a.txt uncompressed size 2 ≠ declared 3") = true := by native_decide


-- COVERAGE TRIPWIRE (test-health). Anchors the last theorem of each section;
-- a swallowed section makes its anchor an unknown identifier and fails `#check`
-- elaboration.
#check @crc32_hi                 -- CRC-32 standard vectors
#check @inflate_empty            -- inflate — bit reader / Huffman unit behavior via...
#check @inflate_rle              -- back-reference / overlapping copy
#check @readZip_deflate          -- ZIP container — synthetic archives (system `zip`)
#check @inflate_reserved_btype   -- error paths (typed, never silent)
#check @inflate_block_fuel_exhausted  -- adversarial reject branches (B3d-A2) — DEFLATE
#check @readZip_size_mismatch    -- adversarial reject branches (B3d-A2) — ZIP

end Zip

end Kue
